server:
  port: 8099

spring:
  application:
    name: frontendserver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

